# Generated by Django 4.1.4 on 2022-12-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the user', max_length=50)),
                ('profession', models.CharField(help_text='user profession', max_length=50)),
                ('job_location', models.CharField(blank=True, help_text='location of the job', max_length=50)),
                ('area_pin', models.IntegerField(blank=True, help_text='Area Code of the location', max_length=7)),
                ('date_of_birth', models.DateField(blank=True, help_text='Birth date')),
            ],
        ),
    ]
