# Generated by Django 4.1.4 on 2022-12-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesLibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='field for movie name', max_length=50, verbose_name='Movie Name')),
                ('director', models.CharField(help_text='field for movie director', max_length=50, verbose_name='Director')),
                ('year', models.IntegerField(blank=True, help_text='field for movie release year', verbose_name='Movie Name')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='field for movie IMDB rating', max_digits=6, verbose_name='Movie Name')),
                ('franchise', models.CharField(blank=True, max_length=50, verbose_name='Franchise')),
            ],
        ),
    ]
