# Generated by Django 4.1.4 on 2022-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslibrarymodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='field for movie IMDB rating', max_digits=6, verbose_name='IMDB Rating'),
        ),
        migrations.AlterField(
            model_name='movieslibrarymodel',
            name='year',
            field=models.IntegerField(blank=True, help_text='field for movie release year', verbose_name='Year of Release'),
        ),
    ]
