# Generated by Django 4.1.4 on 2022-12-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_movieslibrarymodel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslibrarymodel',
            name='director',
            field=models.CharField(help_text='Field for movie director', max_length=50, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movieslibrarymodel',
            name='name',
            field=models.CharField(help_text='Field for movie name', max_length=50, verbose_name='Movie Name'),
        ),
        migrations.AlterField(
            model_name='movieslibrarymodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Field for movie IMDB rating', max_digits=6, verbose_name='IMDB Rating'),
        ),
        migrations.AlterField(
            model_name='movieslibrarymodel',
            name='year',
            field=models.IntegerField(blank=True, help_text='Field for movie release year', verbose_name='Year of Release'),
        ),
    ]
